# Generated by Django 2.2.9 on 2020-01-31 08:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200131_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='content4',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
